name: Publishfdsa

on:
  push:
    branches:
      - master

jobs:
  bump_version:
    name: Bump version, create tag/release point
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bump version and push tag/create release point
        id: bump_version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Repository dispatch tag created event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: pondron/valid8r
          event-type: tag-created
          client-payload: '{"new_version": "${{ steps.bump_version.outputs.new_tag }}"}'

  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: valid8r-v0.1.0-x86_64-linux-gnu.tar.gz
            asset_name: valid8r-v0.1.0-x86_64-linux-gnu.tar.gz
          - os: macos-latest
            artifact_name: valid8r-v0.1.0-x86_64-apple-darwin.tar.gz
            asset_name: valid8r-v0.1.0-x86_64-apple-darwin.tar.gz
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --release --locked
      - name: 'Tar files'
        run: tar -C target/release/ -czvf ${{ matrix.asset_name }} valid8r
      - name: Upload tar to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: v0.1.0